Revert "kernfs: Avoid dynamic memory allocation for small write buffers"
This reverts commit 9efdd6ac80b58fe7c3b8444ba61834aeeb01ab3c.

Causes warning:
fs/kernfs/file.c:267:16: error: stack frame size of 4176 bytes in function 'kernfs_fop_write' [-Werror,-Wframe-larger-than=]
And reportedly doesn't improve anything too much
Thanks @Creeeeger

Signed-off-by: ExtremeXT <75576145+ExtremeXT@users.noreply.github.com>